name: portfolio release
on:
  release:
    types: [published]

jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: 'softwayback/portfolio'

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  CapRover_Deploy_PreProduction:
    if: "github.event.release.prerelease"
    needs: [build_and_push_to_registry]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on prod
        uses: floms/action-caprover@v1
        with:
          host: 'https://caprover.galaxian.dev'
          password: '*'
          app: 'preprod-portfolio'
          image: 'softwayback/portfolio'
          
  CapRover_Deploy_Production:
    if: "!github.event.release.prerelease"
    needs: [build_and_push_to_registry]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on prod
        uses: floms/action-caprover@v1
        with:
          host: 'https://caprover.galaxian.dev'
          password: '*'
          app: 'portfolio'
          image: 'softwayback/portfolio'